/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCostCentersRouteImport } from './routes/_app/cost-centers'
import { Route as AppKeysRouteImport } from './routes/_app/keys'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppAdminCostCentersRouteImport } from './routes/_app/admin/cost-centers'
import { Route as AppAdminEventsRouteImport } from './routes/_app/admin/events'
import { Route as AppAdminLitellmUsersRouteImport } from './routes/_app/admin/litellm-users'
import { Route as AppAdminNotificationsRouteImport } from './routes/_app/admin/notifications'
import { Route as AppAdminProvidersRouteImport } from './routes/_app/admin/providers'
import { Route as AppAdminReportsRouteImport } from './routes/_app/admin/reports'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCostCentersRoute = AppCostCentersRouteImport.update({
  id: '/cost-centers',
  path: '/cost-centers',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCostCentersRoute = AppAdminCostCentersRouteImport.update({
  id: '/admin/cost-centers',
  path: '/admin/cost-centers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEventsRoute = AppAdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLitellmUsersRoute = AppAdminLitellmUsersRouteImport.update({
  id: '/admin/litellm-users',
  path: '/admin/litellm-users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNotificationsRoute = AppAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProvidersRoute = AppAdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/cost-centers': typeof AppCostCentersRoute
  '/keys': typeof AppKeysRoute
  '/profile': typeof AppProfileRoute
  '/requests': typeof AppRequestsRoute
  '/admin/cost-centers': typeof AppAdminCostCentersRoute
  '/admin/events': typeof AppAdminEventsRoute
  '/admin/litellm-users': typeof AppAdminLitellmUsersRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/providers': typeof AppAdminProvidersRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/cost-centers': typeof AppCostCentersRoute
  '/keys': typeof AppKeysRoute
  '/profile': typeof AppProfileRoute
  '/requests': typeof AppRequestsRoute
  '/': typeof AppIndexRoute
  '/admin/cost-centers': typeof AppAdminCostCentersRoute
  '/admin/events': typeof AppAdminEventsRoute
  '/admin/litellm-users': typeof AppAdminLitellmUsersRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/providers': typeof AppAdminProvidersRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/cost-centers': typeof AppCostCentersRoute
  '/_app/keys': typeof AppKeysRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/cost-centers': typeof AppAdminCostCentersRoute
  '/_app/admin/events': typeof AppAdminEventsRoute
  '/_app/admin/litellm-users': typeof AppAdminLitellmUsersRoute
  '/_app/admin/notifications': typeof AppAdminNotificationsRoute
  '/_app/admin/providers': typeof AppAdminProvidersRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cost-centers'
    | '/keys'
    | '/profile'
    | '/requests'
    | '/admin/cost-centers'
    | '/admin/events'
    | '/admin/litellm-users'
    | '/admin/notifications'
    | '/admin/providers'
    | '/admin/reports'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/cost-centers'
    | '/keys'
    | '/profile'
    | '/requests'
    | '/'
    | '/admin/cost-centers'
    | '/admin/events'
    | '/admin/litellm-users'
    | '/admin/notifications'
    | '/admin/providers'
    | '/admin/reports'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/cost-centers'
    | '/_app/keys'
    | '/_app/profile'
    | '/_app/requests'
    | '/_app/'
    | '/_app/admin/cost-centers'
    | '/_app/admin/events'
    | '/_app/admin/litellm-users'
    | '/_app/admin/notifications'
    | '/_app/admin/providers'
    | '/_app/admin/reports'
    | '/_app/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cost-centers': {
      id: '/_app/cost-centers'
      path: '/cost-centers'
      fullPath: '/cost-centers'
      preLoaderRoute: typeof AppCostCentersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/cost-centers': {
      id: '/_app/admin/cost-centers'
      path: '/admin/cost-centers'
      fullPath: '/admin/cost-centers'
      preLoaderRoute: typeof AppAdminCostCentersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/events': {
      id: '/_app/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AppAdminEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/litellm-users': {
      id: '/_app/admin/litellm-users'
      path: '/admin/litellm-users'
      fullPath: '/admin/litellm-users'
      preLoaderRoute: typeof AppAdminLitellmUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/notifications': {
      id: '/_app/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AppAdminNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/providers': {
      id: '/_app/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AppAdminProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCostCentersRoute: typeof AppCostCentersRoute
  AppKeysRoute: typeof AppKeysRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminCostCentersRoute: typeof AppAdminCostCentersRoute
  AppAdminEventsRoute: typeof AppAdminEventsRoute
  AppAdminLitellmUsersRoute: typeof AppAdminLitellmUsersRoute
  AppAdminNotificationsRoute: typeof AppAdminNotificationsRoute
  AppAdminProvidersRoute: typeof AppAdminProvidersRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCostCentersRoute: AppCostCentersRoute,
  AppKeysRoute: AppKeysRoute,
  AppProfileRoute: AppProfileRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminCostCentersRoute: AppAdminCostCentersRoute,
  AppAdminEventsRoute: AppAdminEventsRoute,
  AppAdminLitellmUsersRoute: AppAdminLitellmUsersRoute,
  AppAdminNotificationsRoute: AppAdminNotificationsRoute,
  AppAdminProvidersRoute: AppAdminProvidersRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
