export const ERROR_CODES = [
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'VALIDATION_ERROR',
  'CSRF_ORIGIN_MISMATCH',
  'ACCOUNT_DEACTIVATED',
  'ACCOUNT_INVALID_AFFILIATION',
  'COST_CENTER_NOT_APPROVED',
  'COST_CENTER_EXISTS',
  'COST_CENTER_DEFAULT_IMMUTABLE',
  'COST_CENTER_REQUEST_PENDING',
  'PAID_MODEL_REQUIRES_COST_CENTER',
  'MODEL_NOT_ALLOWED',
  'KEY_BUDGET_EXCEEDS_USER_BUDGET',
  'KEY_NOT_ACTIVE',
  'KEY_INVALID',
  'KEY_TEST_FAILED',
  'LAST_ADMIN',
  'ROLE_MANAGED_BY_IDP',
  'SELF_DEACTIVATION',
  'LITELLM_ERROR',
  'INTERNAL',
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  details?: unknown;
}
